"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import TrustReceipt from "../../components/TrustReceipt";

/**
 * Receipt Detail Page — displays a full Trust Receipt by analysis_id.
 * Now fetching live data from the Veridian API.
 */

export default function ReceiptPage() {
  const { id } = useParams();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchReceipt() {
      try {
        const res = await fetch(`http://localhost:8000/v1/analyze/${id}`);
        if (!res.ok) throw new Error("Receipt not found");
        const json = await res.json();
        
        if (json.trust_receipt) {
          setData(json.trust_receipt);
        } else {
          // If the trust_receipt isn't ready, we might show a pending state
          setError("Analysis is still in progress. Please refresh in a few seconds.");
        }
      } catch (err: any) {
        setError(err.message || "Failed to load receipt");
      } finally {
        setLoading(false);
      }
    }
    if (id) fetchReceipt();
  }, [id]);

  const handleExportPDF = () => {
     window.print();
  };

  if (loading) {
    return (
      <div className="mx-auto max-w-4xl px-6 py-10 animate-pulse">
        <div className="h-6 w-32 bg-gray-800 rounded mb-8"></div>
        <div className="h-96 bg-gray-900 rounded-xl"></div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="mx-auto max-w-4xl px-6 py-10 text-center">
        <h1 className="text-2xl font-bold mb-4">Report Unavailable</h1>
        <p className="text-gray-500 mb-8">{error}</p>
        <a href="/" className="btn-primary px-6 py-2 rounded-lg bg-gray-800">Return to Dashboard</a>
      </div>
    );
  }

  // Prepping props for the component with correct mapping for structured evidence
  const receiptProps = {
    analysisId: id as string,
    overallVerdict: data.verdict || "UNVERIFIABLE",
    overallConfidence: data.confidence || 0.0,
    claimVerdicts: (data.claim_verdicts || []).map((cv: any) => ({
        ...cv,
        evidence_used: (cv.evidence_sources || []).map((ev: any) => ({
            source_url: ev.url,
            source_name: ev.title,
            excerpt: ev.content
        }))
    })),
    mediaType: data.media_type || "text",
    processingTimeMs: data.processing_time_ms || 1200, 
    createdAt: new Date(data.created_at || Date.now()).toLocaleDateString(),
  };

  return (
    <div className="mx-auto max-w-4xl px-6 py-10 print:p-0">
      {/* Back link - hidden during print */}
      <a
        href="/"
        className="mb-6 inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-300 transition-colors print:hidden"
      >
        ← Back to Dashboard
      </a>

      <TrustReceipt {...receiptProps} />

      {/* ── Share section ─────────────────────────────────────────── */}
      <div className="mt-8 flex items-center justify-center gap-4 print:hidden">
        <button 
          onClick={() => navigator.clipboard.writeText(window.location.href)}
          className="rounded-lg bg-gray-800 px-5 py-2.5 text-sm font-medium text-gray-300 hover:bg-gray-700 transition-colors"
        >
          📋 Copy Link
        </button>
        <button 
          onClick={handleExportPDF}
          className="rounded-lg bg-gray-800 px-5 py-2.5 text-sm font-medium text-gray-300 hover:bg-gray-700 transition-colors"
        >
          📄 Export PDF
        </button>
        <button 
          onClick={handleExportPDF}
          className="rounded-lg bg-gradient-to-r from-emerald-500 to-cyan-500 px-5 py-2.5 text-sm font-semibold text-gray-950 hover:opacity-90 transition-opacity"
        >
          🔗 Share Receipt
        </button>
      </div>

      {/* Print-only footer */}
      <div className="hidden print:block mt-10 text-center text-xs text-gray-500">
        Generated by Veridian Misinformation Platform — {new Date().toLocaleString()}
      </div>
    </div>
  );
}

function DetectionCard({
  model,
  score,
  verdict,
  category,
}: {
  model: string;
  score: number;
  verdict: string;
  category: string;
}) {
  const color = score > 0.7 ? "text-red-400" : score > 0.4 ? "text-yellow-400" : "text-emerald-400";

  return (
    <div className="rounded-lg bg-gray-900/40 p-4">
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm font-medium">{model}</span>
        <span className="text-xs text-gray-600 uppercase">{category}</span>
      </div>
      <div className={`text-2xl font-bold ${color}`}>
        {(score * 100).toFixed(0)}%
      </div>
      <p className="mt-1 text-xs text-gray-500">{verdict}</p>
      <div className="mt-2 meter-track">
        <div
          className={`meter-fill ${
            score > 0.7 ? "bg-red-400" : score > 0.4 ? "bg-yellow-400" : "bg-emerald-400"
          }`}
          style={{ width: `${score * 100}%` }}
        />
      </div>
    </div>
  );
}

function TimelineItem({
  step,
  time,
  status,
  detail,
}: {
  step: string;
  time: string;
  status: string;
  detail: string;
}) {
  return (
    <div className="flex items-start gap-4">
      <div className="flex flex-col items-center">
        <div className="flex h-6 w-6 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400 text-xs">
          ✓
        </div>
        <div className="h-full w-px bg-gray-800/60 mt-1" />
      </div>
      <div className="flex-1 pb-4">
        <div className="flex items-center justify-between">
          <span className="text-sm font-medium">{step}</span>
          <span className="text-xs text-gray-600 font-mono">{time}</span>
        </div>
        <p className="mt-0.5 text-xs text-gray-500">{detail}</p>
      </div>
    </div>
  );
}
